services:
  megacmd-tmm:
    container_name: mega-cmd-tmm
    build:
      context: ./megacmd
      dockerfile: Dockerfile
    environment:
      - SRC_FOLDER=${SRC_FOLDER:? SRC_FOLDER must be set to detect files ready for download} # folder on mega from which to download files
      - DEST_FOLDER=${DEST_FOLDER:? DEST_FOLDER must be set to download files onto host machine} # folder on host machine which receives downloaded files
    volumes:
      - megacmd-data:/root/.megaCmd # mega-cmd data directory (stores session, etc.)
      - /temp-data # temporary directory when downloading files
      - ${DEST_FOLDER}:/mega-out # directory into which completed downloads are moved

      - tmm-data:/root/tinyMediaManager/data # tmm data directory (stores scraping configs, etc.)

volumes:
  megacmd-data:
  tmm-data:
